/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdjustedAgeCalculatorRouteImport } from './routes/adjusted-age-calculator'
import { Route as AdjustedAgeVsChronologicalAgeRouteImport } from './routes/adjusted-age-vs-chronological-age'
import { Route as HowToCalculateCorrectedAgeRouteImport } from './routes/how-to-calculate-corrected-age'
import { Route as LatePretermBabyRouteImport } from './routes/late-preterm-baby'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as NicuFollowUpScheduleRouteImport } from './routes/nicu-follow-up-schedule'
import { Route as PmaCalculatorRouteImport } from './routes/pma-calculator'
import { Route as PreemieVaccinesRouteImport } from './routes/preemie-vaccines'
import { Route as PreemieWeightGainRouteImport } from './routes/preemie-weight-gain'
import { Route as PrematureBabyMilestonesRouteImport } from './routes/premature-baby-milestones'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RedFlagsRouteImport } from './routes/red-flags'
import { Route as WhenCanMyPreemieStartSolidsRouteImport } from './routes/when-can-my-preemie-start-solids'
import { Route as WhenToStopCorrectingRouteImport } from './routes/when-to-stop-correcting'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustedAgeCalculatorRoute = AdjustedAgeCalculatorRouteImport.update({
  id: '/adjusted-age-calculator',
  path: '/adjusted-age-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdjustedAgeVsChronologicalAgeRoute =
  AdjustedAgeVsChronologicalAgeRouteImport.update({
    id: '/adjusted-age-vs-chronological-age',
    path: '/adjusted-age-vs-chronological-age',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToCalculateCorrectedAgeRoute =
  HowToCalculateCorrectedAgeRouteImport.update({
    id: '/how-to-calculate-corrected-age',
    path: '/how-to-calculate-corrected-age',
    getParentRoute: () => rootRouteImport,
  } as any)
const LatePretermBabyRoute = LatePretermBabyRouteImport.update({
  id: '/late-preterm-baby',
  path: '/late-preterm-baby',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const NicuFollowUpScheduleRoute = NicuFollowUpScheduleRouteImport.update({
  id: '/nicu-follow-up-schedule',
  path: '/nicu-follow-up-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const PmaCalculatorRoute = PmaCalculatorRouteImport.update({
  id: '/pma-calculator',
  path: '/pma-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PreemieVaccinesRoute = PreemieVaccinesRouteImport.update({
  id: '/preemie-vaccines',
  path: '/preemie-vaccines',
  getParentRoute: () => rootRouteImport,
} as any)
const PreemieWeightGainRoute = PreemieWeightGainRouteImport.update({
  id: '/preemie-weight-gain',
  path: '/preemie-weight-gain',
  getParentRoute: () => rootRouteImport,
} as any)
const PrematureBabyMilestonesRoute = PrematureBabyMilestonesRouteImport.update({
  id: '/premature-baby-milestones',
  path: '/premature-baby-milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RedFlagsRoute = RedFlagsRouteImport.update({
  id: '/red-flags',
  path: '/red-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const WhenCanMyPreemieStartSolidsRoute =
  WhenCanMyPreemieStartSolidsRouteImport.update({
    id: '/when-can-my-preemie-start-solids',
    path: '/when-can-my-preemie-start-solids',
    getParentRoute: () => rootRouteImport,
  } as any)
const WhenToStopCorrectingRoute = WhenToStopCorrectingRouteImport.update({
  id: '/when-to-stop-correcting',
  path: '/when-to-stop-correcting',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adjusted-age-calculator': typeof AdjustedAgeCalculatorRoute
  '/adjusted-age-vs-chronological-age': typeof AdjustedAgeVsChronologicalAgeRoute
  '/how-to-calculate-corrected-age': typeof HowToCalculateCorrectedAgeRoute
  '/late-preterm-baby': typeof LatePretermBabyRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/nicu-follow-up-schedule': typeof NicuFollowUpScheduleRoute
  '/pma-calculator': typeof PmaCalculatorRoute
  '/preemie-vaccines': typeof PreemieVaccinesRoute
  '/preemie-weight-gain': typeof PreemieWeightGainRoute
  '/premature-baby-milestones': typeof PrematureBabyMilestonesRoute
  '/privacy': typeof PrivacyRoute
  '/red-flags': typeof RedFlagsRoute
  '/when-can-my-preemie-start-solids': typeof WhenCanMyPreemieStartSolidsRoute
  '/when-to-stop-correcting': typeof WhenToStopCorrectingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adjusted-age-calculator': typeof AdjustedAgeCalculatorRoute
  '/adjusted-age-vs-chronological-age': typeof AdjustedAgeVsChronologicalAgeRoute
  '/how-to-calculate-corrected-age': typeof HowToCalculateCorrectedAgeRoute
  '/late-preterm-baby': typeof LatePretermBabyRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/nicu-follow-up-schedule': typeof NicuFollowUpScheduleRoute
  '/pma-calculator': typeof PmaCalculatorRoute
  '/preemie-vaccines': typeof PreemieVaccinesRoute
  '/preemie-weight-gain': typeof PreemieWeightGainRoute
  '/premature-baby-milestones': typeof PrematureBabyMilestonesRoute
  '/privacy': typeof PrivacyRoute
  '/red-flags': typeof RedFlagsRoute
  '/when-can-my-preemie-start-solids': typeof WhenCanMyPreemieStartSolidsRoute
  '/when-to-stop-correcting': typeof WhenToStopCorrectingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adjusted-age-calculator': typeof AdjustedAgeCalculatorRoute
  '/adjusted-age-vs-chronological-age': typeof AdjustedAgeVsChronologicalAgeRoute
  '/how-to-calculate-corrected-age': typeof HowToCalculateCorrectedAgeRoute
  '/late-preterm-baby': typeof LatePretermBabyRoute
  '/mcp': typeof McpRoute
  '/methodology': typeof MethodologyRoute
  '/nicu-follow-up-schedule': typeof NicuFollowUpScheduleRoute
  '/pma-calculator': typeof PmaCalculatorRoute
  '/preemie-vaccines': typeof PreemieVaccinesRoute
  '/preemie-weight-gain': typeof PreemieWeightGainRoute
  '/premature-baby-milestones': typeof PrematureBabyMilestonesRoute
  '/privacy': typeof PrivacyRoute
  '/red-flags': typeof RedFlagsRoute
  '/when-can-my-preemie-start-solids': typeof WhenCanMyPreemieStartSolidsRoute
  '/when-to-stop-correcting': typeof WhenToStopCorrectingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adjusted-age-calculator'
    | '/adjusted-age-vs-chronological-age'
    | '/how-to-calculate-corrected-age'
    | '/late-preterm-baby'
    | '/mcp'
    | '/methodology'
    | '/nicu-follow-up-schedule'
    | '/pma-calculator'
    | '/preemie-vaccines'
    | '/preemie-weight-gain'
    | '/premature-baby-milestones'
    | '/privacy'
    | '/red-flags'
    | '/when-can-my-preemie-start-solids'
    | '/when-to-stop-correcting'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adjusted-age-calculator'
    | '/adjusted-age-vs-chronological-age'
    | '/how-to-calculate-corrected-age'
    | '/late-preterm-baby'
    | '/mcp'
    | '/methodology'
    | '/nicu-follow-up-schedule'
    | '/pma-calculator'
    | '/preemie-vaccines'
    | '/preemie-weight-gain'
    | '/premature-baby-milestones'
    | '/privacy'
    | '/red-flags'
    | '/when-can-my-preemie-start-solids'
    | '/when-to-stop-correcting'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adjusted-age-calculator'
    | '/adjusted-age-vs-chronological-age'
    | '/how-to-calculate-corrected-age'
    | '/late-preterm-baby'
    | '/mcp'
    | '/methodology'
    | '/nicu-follow-up-schedule'
    | '/pma-calculator'
    | '/preemie-vaccines'
    | '/preemie-weight-gain'
    | '/premature-baby-milestones'
    | '/privacy'
    | '/red-flags'
    | '/when-can-my-preemie-start-solids'
    | '/when-to-stop-correcting'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdjustedAgeCalculatorRoute: typeof AdjustedAgeCalculatorRoute
  AdjustedAgeVsChronologicalAgeRoute: typeof AdjustedAgeVsChronologicalAgeRoute
  HowToCalculateCorrectedAgeRoute: typeof HowToCalculateCorrectedAgeRoute
  LatePretermBabyRoute: typeof LatePretermBabyRoute
  McpRoute: typeof McpRoute
  MethodologyRoute: typeof MethodologyRoute
  NicuFollowUpScheduleRoute: typeof NicuFollowUpScheduleRoute
  PmaCalculatorRoute: typeof PmaCalculatorRoute
  PreemieVaccinesRoute: typeof PreemieVaccinesRoute
  PreemieWeightGainRoute: typeof PreemieWeightGainRoute
  PrematureBabyMilestonesRoute: typeof PrematureBabyMilestonesRoute
  PrivacyRoute: typeof PrivacyRoute
  RedFlagsRoute: typeof RedFlagsRoute
  WhenCanMyPreemieStartSolidsRoute: typeof WhenCanMyPreemieStartSolidsRoute
  WhenToStopCorrectingRoute: typeof WhenToStopCorrectingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjusted-age-calculator': {
      id: '/adjusted-age-calculator'
      path: '/adjusted-age-calculator'
      fullPath: '/adjusted-age-calculator'
      preLoaderRoute: typeof AdjustedAgeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adjusted-age-vs-chronological-age': {
      id: '/adjusted-age-vs-chronological-age'
      path: '/adjusted-age-vs-chronological-age'
      fullPath: '/adjusted-age-vs-chronological-age'
      preLoaderRoute: typeof AdjustedAgeVsChronologicalAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-calculate-corrected-age': {
      id: '/how-to-calculate-corrected-age'
      path: '/how-to-calculate-corrected-age'
      fullPath: '/how-to-calculate-corrected-age'
      preLoaderRoute: typeof HowToCalculateCorrectedAgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/late-preterm-baby': {
      id: '/late-preterm-baby'
      path: '/late-preterm-baby'
      fullPath: '/late-preterm-baby'
      preLoaderRoute: typeof LatePretermBabyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nicu-follow-up-schedule': {
      id: '/nicu-follow-up-schedule'
      path: '/nicu-follow-up-schedule'
      fullPath: '/nicu-follow-up-schedule'
      preLoaderRoute: typeof NicuFollowUpScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pma-calculator': {
      id: '/pma-calculator'
      path: '/pma-calculator'
      fullPath: '/pma-calculator'
      preLoaderRoute: typeof PmaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preemie-vaccines': {
      id: '/preemie-vaccines'
      path: '/preemie-vaccines'
      fullPath: '/preemie-vaccines'
      preLoaderRoute: typeof PreemieVaccinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preemie-weight-gain': {
      id: '/preemie-weight-gain'
      path: '/preemie-weight-gain'
      fullPath: '/preemie-weight-gain'
      preLoaderRoute: typeof PreemieWeightGainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premature-baby-milestones': {
      id: '/premature-baby-milestones'
      path: '/premature-baby-milestones'
      fullPath: '/premature-baby-milestones'
      preLoaderRoute: typeof PrematureBabyMilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red-flags': {
      id: '/red-flags'
      path: '/red-flags'
      fullPath: '/red-flags'
      preLoaderRoute: typeof RedFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/when-can-my-preemie-start-solids': {
      id: '/when-can-my-preemie-start-solids'
      path: '/when-can-my-preemie-start-solids'
      fullPath: '/when-can-my-preemie-start-solids'
      preLoaderRoute: typeof WhenCanMyPreemieStartSolidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/when-to-stop-correcting': {
      id: '/when-to-stop-correcting'
      path: '/when-to-stop-correcting'
      fullPath: '/when-to-stop-correcting'
      preLoaderRoute: typeof WhenToStopCorrectingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdjustedAgeCalculatorRoute: AdjustedAgeCalculatorRoute,
  AdjustedAgeVsChronologicalAgeRoute: AdjustedAgeVsChronologicalAgeRoute,
  HowToCalculateCorrectedAgeRoute: HowToCalculateCorrectedAgeRoute,
  LatePretermBabyRoute: LatePretermBabyRoute,
  McpRoute: McpRoute,
  MethodologyRoute: MethodologyRoute,
  NicuFollowUpScheduleRoute: NicuFollowUpScheduleRoute,
  PmaCalculatorRoute: PmaCalculatorRoute,
  PreemieVaccinesRoute: PreemieVaccinesRoute,
  PreemieWeightGainRoute: PreemieWeightGainRoute,
  PrematureBabyMilestonesRoute: PrematureBabyMilestonesRoute,
  PrivacyRoute: PrivacyRoute,
  RedFlagsRoute: RedFlagsRoute,
  WhenCanMyPreemieStartSolidsRoute: WhenCanMyPreemieStartSolidsRoute,
  WhenToStopCorrectingRoute: WhenToStopCorrectingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
